spring.application.name=starter-spring-boot-keycloak
spring.profiles.active=dev

#logging.level.org.springframework=debug

springdoc.default-produces-media-type=application/json

#server.servlet.context-path=/api/v1/

springdoc.swagger-ui.use-root-path=true